name: Run Tests 
on:
  workflow_dispatch:
  push:
   branches: [main]
  pull_request:
   types: [opened, synchronize]
   branches: 
     - '*'

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          path: './'

      - name: Parse info.json
        run: jq -e '' info.json

      - name: Evaluate info.json
        run: |
          jq '.[-1]' info.json > userinfo.json 
          jq '.name, .gh_username, .place, .current_pos, .bio' -e userinfo.json

          # Check length of all fields
          jq '.name | length <= 30' -e userinfo.json || {echo "test"}

          jq '.place | length <= 30' -e userinfo.json

          jq '.current_pos | length <= 58' -e userinfo.json

          jq '.bio | length <= 150' -e userinfo.json

          # Check whether image is present
          jq '.image' userinfo.json > userimage 
          if grep -q "null" ./userimage ; then
            echo "Image file not required"
          else
            if [ -f "./images/$(cat ./userimage | cut -d \" -f2)" ]; then
              echo "image verified!"
            else
              echo "image file not found"
              exit 1
            fi
          fi

          size=$(du -k "./images/$(cat ./userimage | cut -d \" -f2)" | cut -f1)
          if [ "$size" -lt "200" ]; then
            echo "image size verified!"
          else
            echo "image size greater than 200!"
            exit 1
          fi

      - name: Cleanup
        run: |
          rm userinfo.json
          rm userimage

