name: Run Tests 
on: 
  [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          path: './'

      - name: Parse info.json
        run: |
          jq < <(cat info.json)

      - name: Evaluate info.json
        run: |
          userInfo=$(jq '.[-1]' < <(cat info.json) ) 
          jq '.name, .gh_username, .email, .place, .current_pos, .bio' -e < <(echo $userInfo) || { 
            echo 'All fields not present in info.json!';
            exit 1; 
          }

          # Check length of all fields
          jq '.name | length <= 30' -e < <(echo $userInfo) || {
            echo 'name length exceeds!';
            exit 1;
        }
          jq '.email | length <= 30' -e < <(echo $userInfo) || {
            echo 'email length exceeds!';
            exit 1;
        }
          jq '.place | length <= 30' -e < <(echo $userInfo) || {
            echo 'place length exceeds!';
            exit 1;
        }
          jq '.current_pos | length <= 58' -e < <(echo $userInfo) || {
            echo 'current_pos length exceeds!';
            exit 1;
        }
          jq '.bio | length <= 150' -e < <(echo $userInfo) || {
            echo 'bio length exceeds!';
            exit 1;
        }

        # Check whether image is present
        userImage=$(jq '.image' < <(echo $userInfo))
        if [[ ! userImage = 'null' ]]; then
          if [ -f "./images/$userImage"]; then
            echo "image verified!"
          else
            echo "image file not found"
            exit 1
          fi
        fi

